In [ ]:
from sklearn.pipeline import Pipeline
## feature scaling
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression


In [ ]:
steps=[("standard_scaler", StandardScaler()),
       ("classifier",LogisticRegression())] #must be supplied in the form of key value pair.

In [ ]:
steps

[('standard_scaler', StandardScaler()), ('classifier', LogisticRegression())]

In [ ]:
pipe=Pipeline(steps)

In [ ]:
# visualize pipeline
from sklearn import set_config


In [ ]:
set_config(display="diagram")

In [ ]:
pipe

Pipeline(steps=[('standard_scaler', StandardScaler()),
                ('classifier', LogisticRegression())])

In [ ]:
## creating a dataset
from sklearn.datasets import make_classification
X,y =make_classification(n_samples=1000)

In [ ]:
X.shape

(1000, 20)

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.33, random_state=42)

In [ ]:
X_train.shape

(670, 20)

In [ ]:
pipe.fit(X_train,y_train)

Pipeline(steps=[('standard_scaler', StandardScaler()),
                ('classifier', LogisticRegression())])

In [ ]:
pipe.predict(X_test)

array([1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1,
       1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1,
       0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0,
       0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1,
       0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1,
       1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1,
       0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1,
       0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0,
       1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0,
       0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1,
       1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1,

# Example 2
## Displaying a pipeline with standard scaler , dimensionality reduction and then estimator

In [ ]:
from sklearn.decomposition import PCA
from sklearn.svm import SVC


In [ ]:
steps=[("scaling",StandardScaler()),
       ("PCA",PCA(n_components=5)),
       ("SVC",SVC())]

In [ ]:
pipe2=Pipeline(steps)

In [ ]:
pipe2['scaling'].fit_transform(X_train)

array([[-0.64413646, -0.08826083,  0.59307829, ...,  0.64365486,
        -0.67095089, -1.1521928 ],
       [ 1.06447581,  0.33961799, -0.71126207, ..., -0.61135852,
         0.29801318, -1.16947566],
       [-0.71216841, -0.66135539, -1.14836694, ..., -0.42853658,
        -0.64482586,  0.79101648],
       ...,
       [-1.18975833,  0.81118867,  1.44256283, ..., -0.72856611,
        -0.40525321, -1.44394195],
       [ 0.62797223, -1.62450024, -0.19550765, ...,  1.56801731,
         0.29084958,  0.42171149],
       [ 1.86030535, -0.57071441,  0.43464819, ...,  0.4911462 ,
         1.24400083, -1.97919781]])

In [ ]:
pipe2.fit(X_train,y_train)

Pipeline(steps=[('scaling', StandardScaler()), ('PCA', PCA(n_components=5)),
                ('SVC', SVC())])

In [ ]:
pipe2.predict(X_test)

array([1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1,
       1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0,
       0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1,
       0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0,
       0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1,
       0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1,
       1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1,
       0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1,
       0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1,
       1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0,
       0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1,
       0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1,
       1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1,

## Complex examples of columns transformer

In [ ]:
from sklearn.impute import SimpleImputer # for numerical data

In [ ]:
import numpy as np


In [ ]:
## for numerical processing pipeline
numeric_processor=Pipeline(
    steps=[
        ("imputation_mean",SimpleImputer(missing_values=np.nan,strategy='mean')),
        ("scaler",StandardScaler())
    ]
)

In [ ]:
numeric_processor

Pipeline(steps=[('imputation_mean', SimpleImputer()),
                ('scaler', StandardScaler())])

In [ ]:
## for categorical processing pipeline
from sklearn.preprocessing import OneHotEncoder
categorical_processor=Pipeline(
    steps=[
        ("imputation_mean",SimpleImputer(fill_value='missing',strategy='constant')),
        ('onehot',OneHotEncoder(handle_unknown='ignore'))
    ]
)

In [ ]:
## combine processing techniques
from sklearn.compose import ColumnTransformer

In [ ]:
preprocessor=ColumnTransformer(
    [("categorical",categorical_processor,['gender','city']),
     ("numerical",numeric_processor,["age","height"])]
)

In [ ]:
preprocessor

ColumnTransformer(transformers=[('categorical',
                                 Pipeline(steps=[('imputation_mean',
                                                  SimpleImputer(fill_value='missing',
                                                                strategy='constant')),
                                                 ('onehot',
                                                  OneHotEncoder(handle_unknown='ignore'))]),
                                 ['gender', 'city']),
                                ('numerical',
                                 Pipeline(steps=[('imputation_mean',
                                                  SimpleImputer()),
                                                 ('scaler', StandardScaler())]),
                                 ['age', 'height'])])

In [ ]:
from sklearn.pipeline import make_pipeline


In [ ]:
pipe=make_pipeline(preprocessor,LogisticRegression())

In [ ]:
pipe

Pipeline(steps=[('columntransformer',
                 ColumnTransformer(transformers=[('categorical',
                                                  Pipeline(steps=[('imputation_mean',
                                                                   SimpleImputer(fill_value='missing',
                                                                                 strategy='constant')),
                                                                  ('onehot',
                                                                   OneHotEncoder(handle_unknown='ignore'))]),
                                                  ['gender', 'city']),
                                                 ('numerical',
                                                  Pipeline(steps=[('imputation_mean',
                                                                   SimpleImputer()),
                                                                  ('scaler',
                                                                   StandardScaler())]),
                                                  ['age', 'height'])])),
                ('logisticregression', LogisticRegression())])